// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skqmytjjnzrltongqsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcW15dGpqbnpybHRvbmdxc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzA3MjMsImV4cCI6MjA1OTQ0NjcyM30.CgC1Ersv4zT81NG1jKVun85_-OQnKeAFeq4vEEpFlr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);